service:
  name: sls-mackerel-alert-pixela

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  stage: prod
  region: ap-northeast-1

functions:
  endpoint:
    handler: src/handler.run
    environment:
      PIXELA_USER: ''
      PIXELA_TOKEN: ''
      PIXELA_GRAPH_ID: ''
    events:
      - http:
          method: post
          path: endpoint
